# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160621_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2016, 7, 9), null=True),
        ),
    ]
