# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160713_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2016, 7, 16), null=True),
        ),
    ]
